### ISSUE TITLE
Colour picker display problem

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/story-tools-composer#102]
The color picker for basic styling doesn’t display correctly. This sounds like a simple one but I have not been able to determine why. Probably a dependency issue.

**Comment by lhcramer** [comment]
Good resource for hex value defaults http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

**Comment by Coop56** [comment]
If we can't get this color picker working, we can choose a new color picker instead @goudine.

**Comment by goudine** [comment]
Putting ticket back as colorpicker was not implemented.

Branches in progress are https://github.com/MapStory/story-tools/tree/spectrum & https://github.com/MapStory/story-tools-composer/tree/spectrum in the story-tools and story-tools-composer repos respectively.

Documentation for spectrum available here: https://bgrins.github.io/spectrum/
Git repos here: https://github.com/bgrins/spectrum
