### ISSUE TITLE
Label outlines

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/story-tools-composer#103]
Within the Styling dialog the `label` submenu has 5 font options (bold, underline, italics, etc). These are not functional on `story-tools-composer` based composer however, some (bold and italics) are operational on prod with `maploom` based composer. 

![image](https://user-images.githubusercontent.com/5894255/38880676-26304f9a-421b-11e8-82b3-1fbb0c7cf402.png)

Acceptance Criteria: 

- [ ] have the label for the layer within composer reflect the selected font style 
- [ ] _or_ verify that the font style is not possible within SLD/OL3

**Comment by lhcramer** [comment]
@darinacosta are these acceptance criteria correct?
