### ISSUE TITLE
Edit Story Info modal doesn't close properly

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/story-tools-composer#104]
Reported by @darinacosta: After clicking “save” from the “Edit Story Info” modal, the modal doesn’t get dismissed.

**Comment by Coop56** [comment]
Rather than having the save button immediately close the modal, we're going to add a Close button next to it.

**Comment by cuttlefish** [comment]
I noticed a couple of days ago that there are several modals that don't close. Is this common code between them all?
