### ISSUE TITLE
Opening composer from a layer detail page should automatically load the layer

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/story-tools-composer#108]
Reported by @jonpmarino: When launching composer from layer detail page, Ch 1 in composer should load that layer.

**Comment by jonpmarino** [comment]
on lab.mapstory.org as of July 20 I get a broken page when clicking the "compose story" button on a layer detail.

![screen shot 2018-07-20 at 12 18 54 pm](https://user-images.githubusercontent.com/2573761/43025374-213b42cc-8c37-11e8-9e5a-d77c2e37758b.jpg)

**Comment by jpierson-boundlessgeo** [comment]
Desired functionality is to be able to create a story directly from the layer page
