### ISSUE TITLE
Add tooltip to StoryFrame reticule

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/story-tools-composer#111]
Reported by @jonpmarino: In StoryFrames, add tooltip over Reticule to tell user to "Select the area for your StoryFrame"

**Comment by goudine** [comment]
Verified on [staging](https://staging.mapstory.org/story/498/draft)
<img width="444" alt="storyframe_tooltip" src="https://user-images.githubusercontent.com/17364268/38830757-2665dd94-4172-11e8-8c0a-7b4146602c8e.png">
