### ISSUE TITLE
Layers don't play after Chapter 1 in Stories

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/story-tools-composer#119]
As a user, I expect that layers in my stories will "play". Currently (staging.mapstory.org) when I advance to any chapter after chapter 1 and hit play, the data in my layers don't seem to advance.

Example - https://staging.mapstory.org/story/jacks-and-spades/.

Advance to Chapter 2 and hit play.

**Comment by goudine** [comment]
Multi-chapter stories only show the 1st chapter in the viewer when hitting play.

See stories created using [admin account](https://staging.mapstory.org/story/multi-chapter-test/) & [personal account](https://staging.mapstory.org/story/chapter-test-personal-acount/)

**Comment by zunware** [comment]
@goudine I'm having a similar issue where changing chapters doesn't update the storypins: #121 .
