### ISSUE TITLE
StoryPins remain the same when changing chapters 

### ISSUE THREAD

**Issue by zunware** [MapStory/story-tools-composer#121]
When you have a story with multiple chapters and switch between them there is no change on the storypins that get shown.

**Comment by jonpmarino** [comment]
re-opening. Seems to be still happening on prod. Just published https://mapstory.org/story/american-political-development-august-4/ and I see pins for chapter 2 on chapter 1.

![screen shot 2018-09-04 at 3 34 01 pm](https://user-images.githubusercontent.com/2573761/45056347-49688f80-b058-11e8-899b-8f5839273faa.jpg)
