### ISSUE TITLE
styles on layers don't seem to persist on stories.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/story-tools-composer#123]
**Expected Behavior:**

Once I style a layer in my story, I expect that style to remain unchanged as I continue working on other parts of my story, or publish my story and have it play.

**Problem**

On current build of staging, it doesn't seem like style changes persist. Once I change a style and go to other parts of composer (such as pins or frames) and then return to the layer styler, the style switches back from what I created to the default orange.

Also, if I recreate my style and publish my story, the viewer shows the default orange, not the style I created it.

In screenshots below:

1) I created a style on a points layer with green crosses:

![screen shot 2018-04-07 at 9 01 13 am](https://user-images.githubusercontent.com/2573761/38455812-be668c06-3a42-11e8-81cb-30db6fdea7a0.jpg)

2) Then I moved to work on storypins, and came back to the styler. when I re-opened the styler, the layer style automatically returned to orange and the style I created was lost.

![screen shot 2018-04-07 at 9 01 29 am](https://user-images.githubusercontent.com/2573761/38455819-e5088da0-3a42-11e8-8c6e-bb1b8b72a25a.jpg)

3) I recreated the green crosses style again and published my story. On the viewer, again the style has defaulted to orange circles.

![screen shot 2018-04-07 at 9 02 16 am](https://user-images.githubusercontent.com/2573761/38455823-f608fefa-3a42-11e8-8253-c4dbba9798ce.jpg)

https://staging.mapstory.org/story/testing-styling-persistence/

**Comment by Coop56** [comment]
Duplicate, closing.
