### ISSUE TITLE
Persistance problems

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/story-tools-composer#124]
Quoting @jonpmarino:

> I noticed when I "change published story" and go back into composer, it looks like the Chapter Info for Chapter 1 is gone in the form, but still is there if you go to Preview. Strange. I notice when I advance to Ch 2, the chapter info is still there though, and then when I go back to Chapter 1, its magically back in the form.

> In general it seems we have issues with persisting elements of a story when you click "change published story".

**Comment by Coop56** [comment]
@darinacosta So this isn't a persistence issue - it's the issue we saw before where the data isn't immediately initialized when you hit the page.
