### ISSUE TITLE
Story doesn't save & URL doesn't update with multiple chapters

### ISSUE THREAD

**Issue by darinacosta** [MapStory/story-tools-composer#125]
If there are multiple chapters, it doesn’t refresh the page with the new slug in the url; if it’s only one chapter, it does.

**Comment by darinacosta** [comment]
This is the problem: https://github.com/MapStory/story-tools-composer/blob/master/app/state/stateSvc.js#L432

Pin arrays are sometimes undefined and erroring out

**Comment by cuttlefish** [comment]
According to @Coop56 it doesn't work with multiple chapters.
