### ISSUE TITLE
Unique payload requests do not contain correct data.

### ISSUE THREAD

**Issue by darinacosta** [MapStory/story-tools-composer#152]
To reproduce: 
    - Enter a MapLoom (Composer) session on mapstory.org using this dataset: https://mapstory.org/layers/american_civil_war_9490abe1
    - Add unique styling, select the attribute `result` and a color ramp in the Classification section. 
    - Observe the robust POST payload for this styling request. 

Here's a breakpoint you can add on mapstory.org to get started: 
<img width="1165" alt="screen shot 2018-04-18 at 12 29 34 pm" src="https://user-images.githubusercontent.com/5116937/38948147-4b1554ec-4304-11e8-8c0a-261d4635aeae.png">

**Comment by zunware** [comment]
![Screen Shot 2018-05-30 at 1.00.54 PM.png](https://images.zenhubusercontent.com/5ad4fed04b5806bc2bcf554a/d47146b3-4127-4de5-875a-23208f8f05f5)

**Comment by zunware** [comment]
![Screen Shot 2018-05-30 at 1.02.55 PM.png](https://images.zenhubusercontent.com/5ad4fed04b5806bc2bcf554a/c73319e1-7df5-4f35-85ef-d2f6719adc8b)

**Comment by darinacosta** [comment]
https://github.com/MapStory/story-tools-composer/issues/165 resolves this error

**Comment by zunware** [comment]
This has been fixed by: https://github.com/MapStory/story-tools-composer/issues/165
