### ISSUE TITLE
Icon Commons styling for point layers in composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/story-tools-composer#193]
For stories, a user should be able to style a point layer by applying an svg icon that has been uploaded by a user via the Icons Commons. 

This is implemented at an MVP level currently on MapStory.org prod. There a user can click "icons commons" in the point styling area, search for icons that have been uploaded, and apply it to their layer in their story. See screenshots below.

For MVP in the new composer, we would like to achieve feature parity for icons styling.

![screen shot 2018-05-22 at 12 36 43 pm](https://user-images.githubusercontent.com/2573761/40380033-7d9c253e-5dbd-11e8-9d8f-e601971e8ac8.jpg)
![screen shot 2018-05-22 at 12 37 00 pm](https://user-images.githubusercontent.com/2573761/40380047-82705b2a-5dbd-11e8-9709-0f6783e5499c.jpg)
![screen shot 2018-05-22 at 12 37 25 pm](https://user-images.githubusercontent.com/2573761/40380056-881a182c-5dbd-11e8-92cf-32bd4f4f3355.jpg)

**Comment by darinacosta** [comment]
Branch: https://github.com/MapStory/story-tools/tree/icon-commons
This should be returning a promise but it's not. Figure out why: https://github.com/MapStory/story-tools/blob/icon-commons/lib/ng/edit/style/services/iconCommons.js#L39
