### ISSUE TITLE
Update Story-tools build process to transpile from ES6 to ES5.

### ISSUE THREAD

**Issue by darinacosta** [MapStory/story-tools-composer#243]
Add a step to the Story-tools Gulp build process that pipes the code through an ES6-to-ES5 transpiler. Currently the `scripts` step builds the code for the Composer project: https://github.com/MapStory/story-tools/blob/master/gulpfile.js#L296

**Comment by j-meyer** [comment]
https://github.com/MapStory/story-tools/pull/316
