### ISSUE TITLE
Prevent adding duplicate layers to a chapter

### ISSUE THREAD

**Issue by shawnkendrick** [MapStory/story-tools-composer#298]
If a user adds a layer that has already been added within a chapter, the application throws an error.

"Error: Cannot add item: item with id ... already exists"

When a user adds a layer, we need to check the chapter config to see if the layer has already been added. If it has, the user should not be able to add the layer, and a message should be displayed in the UI to let them know they have attempted to add a duplicate layer to the chapter.

**Comment by Coop56** [comment]
Alternatively, we could simply not show the user the layer in their search results if it's already been added.
